### PR TITLE
Support Symfony 7.x

### PR DESCRIPTION
**Pull request by pfuhrmann**
Ref: https://symfony.com/blog/symfony-7-0-0-released

### CODE REVIEW

**Comment by pfuhrmann** [comment]
cc @wasinger please check

**Comment by wasinger** [comment]
Unfortunately unit tests do not pass, some method signature must have been changed in Symfony 7. @pfuhrmann could you look into this problem? Otherwise I will do it later.

**Comment by pfuhrmann** [comment]
@wasinger I have run the tests locally, should be all good now

**Comment by wasinger** [comment]
@pfuhrmann Thanks for your contribution!

**Pull request merged**
